### ISSUE TITLE
Graph Panel - Brain Connections [all workflows]

### ISSUE THREAD

**Issue by annacanal** [softmatterlab/Braph-2.0-Matlab#1045]
Two times color and thickens buttons in Graph Panel, on the brain view window.
![Screenshot 2021-09-29 at 16 44 11](https://user-images.githubusercontent.com/31701548/135418814-b128deaa-00eb-49c4-b04b-22f47f727037.png)

**To Reproduce**
1. Go to Analysis or Comparison
2. Calculate a nodal measure, such as Degree
3. Visualize that measure
4. Press Brain view
5. Go to Brain connections icon, leading to Graph panel
6. Play with color and thickens buttons. some of them give errors. Moreover, there is redundancy of color and thickness buttons.

**Comment by egolol** [comment]
can we meet to decide final version?
