### ISSUE TITLE
Properties - Personalization window

### ISSUE THREAD

**Issue by annacanal** [softmatterlab/Braph-2.0-Matlab#1069]
- [x] Add a column named tag, to rename labels of the GUI
- [x] when adding numbers out of the order, like 6 or -1 in the following case, an error appears:
```
Error while evaluating Table CellEditCallback.

Error using find
Second argument must be a positive scalar integer.

Error in GUI/cb_personalize/cb_edit_tb (line 325)
                    elseif any(find(cell2mat(data(:, 2)),  newdata))  % repeating value
 
Error while evaluating Table CellEditCallback.
```
- [x] when you re-order, one should keep the rest order

![Screenshot 2021-10-25 at 18 48 57](https://user-images.githubusercontent.com/31701548/138737775-675856ae-1ed2-4d3a-ad50-8c39d090f03c.png)

**Comment by egolol** [comment]
Could someone explain the first point? @annacanal @giovannivolpe
