### ISSUE TITLE
Calculate Degree Assortativity coefficient

### ISSUE THREAD

**Issue by mitemijalkov** [softmatterlab/Braph-2.0-Matlab#110]
Implement the degree assortativity coefficient.

**Comment by annacanal** [comment]
Am I suppose to implement the assortativity coefficient for these for cases in one function or in 4 different measure functions like in braph1? :

- Assortativity coefficient for in - in degree
- Assortativity coefficient for in - out degree
- Assortativity coefficient for out - out degree
- Assortativity coefficient for out - in degree

**Comment by annacanal** [comment]
I guess this can be a rule sent through the graph for directed graphs when calculating assortativity. Like:
'DirectedAssortativityRule' with these 4 cases
So I make all the assortativity coefficients in one measure class. Is this ok @giovannivolpe  ?

**Comment by giovannivolpe** [comment]
We already discussed it in person, but just to keep track of things, it should be 4 classes.
