### ISSUE TITLE
Calculate Path transitivity

### ISSUE THREAD

**Issue by mitemijalkov** [softmatterlab/Braph-2.0-Matlab#139]
Calculate path transitivity. Current implementation is only for BU graphs, we can discuss how to extend the definition for the other types of graphs.

**Comment by annacanal** [comment]
@mitemijalkov is there any paper, in particular, to check for this measure or just from BCT?

**Comment by mitemijalkov** [comment]
@annacanal The reference for the measure is the one given within the code of BCT. I got the idea that this measure is useful from the same paper, and I am not aware of another paper that deals with this measure.
