### ISSUE TITLE
Abstract Class Measurement

### ISSUE THREAD

**Issue by giovannivolpe** [softmatterlab/Braph-2.0-Matlab#159]
- [x] Add class Measurement with fields groups, atlases (see subjects)

- [x] create folder measurements and concrete classes for all

- [x] create relative test functions

**Comment by egolol** [comment]
Measurement can have groups and atlases right? So, its dictionary is a : Containers.Map(key,value) or a Containers.Map(key , Containers.Map (key2, value)). To me its seems like the second option. If we are going to save differente measures per atlas per group.

**Comment by giovannivolpe** [comment]
I think it should have two cell arrays: atlases and datas
This can be implemented as atlases is implemented in Subject
If needed, we can discuss on Skype after 4

**Comment by egolol** [comment]
Yeah, lets discuss it. The thing is, Measurement (abstract) will have a dictionary containing measurements (subclasses)?
