### ISSUE TITLE
Analysis Calculation

### ISSUE THREAD

**Issue by giovannivolpe** [softmatterlab/Braph-2.0-Matlab#179]
- [x] Add ID to Measurement + getID() + Add ID as first parameter in Measurement constructor

- [x] Add getMeasurementIDs() to Analysis

- [x] Add abstract function calculateMeasurementID( ... measure, groups, ... )

- [x] add public function createMeasurement( ... measure, groups, ... )

- [x] Add abstract functions calculate_measurement()

- [x] contains_measurement should accept measurement (pointer to an obj), measurement_index or measurement_id

- [x] getMeasurementIndex should accept measurement (pointer to an obj) or measurement_id

- [x] check other necessary changes to functions in Analysis

- [x] implement concrete classes

**Comment by egolol** [comment]
added getCohort()

**Comment by egolol** [comment]
@giovannivolpe unoficial pull request. what do you think?

**Comment by egolol** [comment]
This is deprecated solved in #210
