### ISSUE TITLE
Comment package Graph

### ISSUE THREAD

**Issue by egolol** [softmatterlab/Braph-2.0-Matlab#231]
- [x] graph/are_compatible
- [x] graph/binarize
- [x] graph/measures/Assortativity
- [x] graph/measures/BetweennessCentrality
- [x] graph/measures/Clustering
- [x] graph/measures/ClusteringAV
- [x] graph/measures/Diameter
- [x] graph/measures/Distance
- [x] graph/measures/EccentricityAv
- [x] graph/measures/EdgeBetweennessCentrality
- [x] graph/measures/EdgeNUmberDistance
- [x] graph/measures/GlobalEfficenciencyAv
- [x] graph/measures/InDegree
- [x] graph/measures/InDegreeAv
- [x] graph/measures/InEccentricityAv
- [x] graph/measures/InGlobalEfficiencyAv
- [x] graph/measures/InInAssortativity
- [x] graph/measures/InLocalEfficiency
- [x] graph/measures/InLocalEfficiencyAv
- [x] graph/measures/InOutAssortatiivity
- [x] graph/measures/InPathLength
- [x] graph/measures/InStrengthAv
- [x] graph/measures/LocalEfficiency
- [x] graph/measures/LocalEfficiencyAv
- [x] graph/measures/OutDegree
- [x] graph/measures/OutDegreeAv
- [x] graph/measures/OutEccentricityAv
- [x] graph/measures/OutGlobalEfficiencyAv
- [x] graph/measures/OutInAssortativity
- [x] graph/measures/OutLocalEfficiency
- [x] graph/measures/OutLocalEfficiencyAv
- [x] graph/measures/OutOutAssortativity
- [x] graph/measures/OutPathLengthAv
- [x] graph/measures/OutStrengthAv
- [x] graph/measures/PathLengthAv
- [x] graph/measures/Radius
- [x] graph/measures/StrengthAv
- [x] graph/measures/Transitivity
- [x] graph/measures/Triangles

**Comment by annacanal** [comment]
Can we work on this more than one person?
What is your idea @egolol

**Comment by egolol** [comment]
can create a communal branch and everyone pushes to the same branch, choose a item on the list and comment it, until they are all done.. 
or... 
open a branch per point an review each one as in the past.

**Comment by annacanal** [comment]
Let's create a collaborative branch, but when choosing an item here, let's write the name, so there is no misunderstanding ^^

**Comment by annacanal** [comment]
Should I remove this function, which appears in OutDegree and InDegree. but not in the rest of the measures:
        function bool = is_compatible_graph(g)
            
            bool = g.is_directed();
        end
I believe with this one down, we don't need is_compatible_graph:
        function list = getCompatibleGraphList()
