### ISSUE TITLE
Improvements to Graph

### ISSUE THREAD

**Issue by giovannivolpe** [softmatterlab/Braph-2.0-Matlab#281]
- [x] Add TYPE_DESCRIPTION
- [x] Reformat the other constants as TYPE (add numbers and structures)

**Comment by annacanal** [comment]
Reformat the other constants as TYPE (add numbers and structures)

Do you mean to have a CONNECTION_TYPE , EDGE_TYPE, SELFCONNECTIVITY_TYPE and NEGATIVITY_TYPE?
