### ISSUE TITLE
Warning in PlotBrainAtlas

### ISSUE THREAD

**Issue by egolol** [softmatterlab/Braph-2.0-Matlab#350]
- [x] Revise warning in PlotBrainAtlas that occurs when testing
- [x] check capitalization of test function

**Comment by giovannivolpe** [comment]
This is the working:

Running test_PlotBrainAtlas
..Warning: Table variable names were modified to make them valid MATLAB identifiers. The original names are
saved in the VariableDescriptions property. 
.
Done test_PlotBrainAtlas
