### ISSUE TITLE
Final check GUIBrainAtlas / package atlas

### ISSUE THREAD

**Issue by giovannivolpe** [softmatterlab/Braph-2.0-Matlab#424]
This is the final check of the subpackage atlas. Everything should be working smoothly from the point of view of a user (both a GUI user and a comman-line user). Also the documentation should be clear and useful to the users.

- [ ] Check carefully GUIBrainAtlas and the whole package atlas
- [ ] Open issues if you find any bugs or problems
- [ ] Create new branches if you want to make any edits

**Comment by annacanal** [comment]
In which branch should we check it? @giovannivolpe

**Comment by egolol** [comment]
@annacanal develop branch
