### ISSUE TITLE
GUI Brain Atlas: Opening GUI in Windows OS

### ISSUE THREAD

**Issue by annacanal** [softmatterlab/Braph-2.0-Matlab#432]
When opening the GUI Brain Atlas in Windows 10, the Matlab window is too high with no access to this:
![image](https://user-images.githubusercontent.com/31701548/85305028-c58dca80-b4ac-11ea-957b-0e2dba163beb.png)

So at first it looks like:
![image](https://user-images.githubusercontent.com/31701548/85305597-92980680-b4ad-11ea-87fb-2ebe35e3c7c4.png)

And the problem is that one cannot move the window down. So first it has to be adjusted the width in order to be able to move the windows down.

I am using Matlab R2020a (but I also had this problem with Matlab R2017 in braph1)

**Comment by egolol** [comment]
solved in #437

**Comment by egolol** [comment]
solved in #439

**Comment by egolol** [comment]
solved in #439
