### ISSUE TITLE
GUI Brain Atlas: Atlas data visualization

### ISSUE THREAD

**Issue by annacanal** [softmatterlab/Braph-2.0-Matlab#434]
When maximizing the window, there is a lot of space on the right of notes. It could be interesting to adapt the sizes of Label, Notes and so to take advantage of all the space available
![image](https://user-images.githubusercontent.com/31701548/85308818-01775e80-b4b2-11ea-977b-2efe386b8134.png)

**Comment by egolol** [comment]
solved in #439
