### ISSUE TITLE
Analysis DTI

### ISSUE THREAD

**Issue by giovannivolpe** [softmatterlab/Braph-2.0-Matlab#497]
Write according to new format (see #487 )

- [x] AnalysisDTI
- [x] test_AnalysisDTI
Do this in collaboration with @egolol and in parallel to issue #496 

**Branch from gv-analysis-final**

**Comment by annacanal** [comment]
Shouldn't we branch from the updated branches that have SubjectDTI and MeasurementDTI?

**Comment by giovannivolpe** [comment]
> Shouldn't we branch from the updated branch that has MeasurementDTI #490 ?

In that case you'll be missing the latest updates in gv-analysis-final. The simplest solution is that you merge the current version of gv-analysis-final into the branch where you are working, so that you have all updates.
