### ISSUE TITLE
ComparisonDTI

### ISSUE THREAD

**Issue by giovannivolpe** [softmatterlab/Braph-2.0-Matlab#526]
**Branch from and merge to gv-analysis-comparison**

- [ ] ComparisonDTI
- [ ] test_ComparisonDTI

Use as reference ComparisonMRI

Double-check with @egolol, see issue #525

**Comment by annacanal** [comment]
I think this should be added in the branch #517 ; where This Comparison has been added according to #514.
So there I can update with the new commits available in #525
