### ISSUE TITLE
Clustering coefficient BU graph

### ISSUE THREAD

**Issue by mitemijalkov** [softmatterlab/Braph-2.0-Matlab#59]
Calculate clustering coefficient for Binary Undirected graphs.

**Comment by giovannivolpe** [comment]
First implement triangle (#60) and then use this for the clustering

**Comment by annacanal** [comment]
@mitemijalkov  Should I create the function ClusteringBU or Clustering with the case BU so far? Also, I could implement WU, since the formula is almost the same as BU.

**Comment by mitemijalkov** [comment]
I have sent the triangles for the review of Giovanni. Hopefully we can have it merged with develop branch soon and you would be free to follow the structure of triangles to create the clustering.
