### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by giovannivolpe** [softmatterlab/Braph-2.0-Matlab#62]
- [x] add function normalize(A, 'NormalizeRule', RULE) to graph
RULE can be 'rescale' (A/max(A)) or 'one'|1 (A<0 = 0 and A>1 = 1). 

- [x] Comment function

- [x] Check this i the constructors of GraphWD (and therefore WU)

- [x] Explain this in the getDescription() of GraphWD and GraphWU

- [x] create test_normalize

**Comment by annacanal** [comment]
The function will be called standardize to avoid problems with the already existing matlab function normalize()
