### ISSUE TITLE
checkValue bug

### ISSUE THREAD

**Issue by egolol** [softmatterlab/Braph-2.0-Matlab#786]
**Describe the bug**
In PlotBrainAtlas, when you pass a wrong size (syms_size, sphs_size, ids_size, labs_size)  it produces a wrong message.

**To Reproduce**
1. Create a PlotBrainAtlas.
2. Pass a wrong syms_size vector, example: if the BrainAtlas has 5 regions, then give argument ('syms_size', [1:1:7]) 
3. Error: BRAPH2:PlotBrainAtlas:WrongInput Error while checkingPlotBrainAtlas with 43 properties bkgcolor = num[1 3] [ 0.95        0.95        0.95 ].
syms_size.

**Expected behavior**
A clear and concise error.

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10 MatlabR2020a

**Smartphone (please complete the following information):**

**Additional context**

**Comment by giovannivolpe** [comment]
@egolol you need to define msg in check_value to produce a specific message.
msg should only be set if there is an error. 
See _BrainSurface.gen.m for some concrete examples.
