### ISSUE TITLE
Bug with the creation of BU/BD graphs

### ISSUE THREAD

**Issue by mitemijalkov** [softmatterlab/Braph-2.0-Matlab#82]
I was not sure where to submit this so I submit this bug as an issue.

When the BU/BD graphs are created, the matrix A associated with the graph is turned into logical matrix (accessed by the getA() method). This creates a problem with the performance of matrix multiplication in the measures (gives the following error: Error using  * 
Both logical arguments must be scalar. Use TIMES (.*) for elementwise multiplication.)
I double checked, and I think the problem is in the implementation of the function binarize.

What do you think? Should this be changed?

**Comment by giovannivolpe** [comment]
Solved with pull request #83. Please, check.
