### ISSUE TITLE
Community Structure of a Graph

### ISSUE THREAD

**Issue by mitemijalkov** [softmatterlab/Braph-2.0-Matlab#88]
Calculate a community structure of a graph. Also write the corresponding test function.

For the calculation, two parameters need to be passed: algorithm that will be used in calculation (Louvain and Newman) and gamma parameters (that defines the resolution of the community).

Issues to decide: 
1) How the community will be implemented for a graph. It is not nodal or global measure in the traditional sense, but the output is indeed a number for each node (number of community to which it participates).
2) Whether to use the optimization procedure described in other toolboxes. The procedure entails calculating the community structure few times (typically 10 or 100) and use the structure that produces maximum modularity.

**Comment by giovannivolpe** [comment]
@egolol wait before working on this. I want to think a bit about the details.
