### ISSUE TITLE
Add covariates in Subjects

### ISSUE THREAD

**Issue by annacanal** [softmatterlab/Braph-2.0-Matlab#889]
- [x] Add fixe covariates (age, sex) in all Subjects
- [x] Add a boolean for controlling if they should be used (true) or not (false) when creating correlation matrix /structural data) or regressed with the measures' results (functional)
- [x] Update Correlation and structural analyses
- [ ] Update in connectivity and functional workflows: regress covariates with the measures' results

**Comment by giovannivolpe** [comment]
The regression from the measures should be done in a different element, which takes in the Group and the MeasureEnsemble or we can modify MeasureEnsemble to give this option.
