### ISSUE TITLE
Open the gui

### ISSUE THREAD

**Issue by hellorp1990** [softmatterlab/Braph-2.0-Matlab#932]
Hi,

I am unable to open the GUI. I ran the braph2genesis file and the file generated braph2 folder. Then I ran the braph2.m file inside the braph2 folder and its didnt do anything. 

Can anyone tell me how to open the gui like the BRAPH 1 version?

Thank you

**Comment by egolol** [comment]
Hi,
BRAPH 2.0 is not released yet, please wait until further notice. You could try the command line for now.

Best regards
