### ISSUE TITLE
Calculate Path Length

### ISSUE THREAD

**Issue by mitemijalkov** [softmatterlab/Braph-2.0-Matlab#97]
Using the distance function, calculate path length of each node.

Path length can be calculated for BU and WU graph. For BD and WD graphs, calculate In and Out -  path length for all nodes.

For binary graphs, path length is based on the number of edges needing to reach one node starting from the other. For weighted graphs, the calculation is based on the weights of the edges (Dijkstra's algorithm). Since we have distance based on the number of edges, maybe this variant can be implemented for weighted graphs also.

**Comment by egolol** [comment]
Talking with Giovanni, we are going to change the settings rule to choose the mean  to this class.
