### ISSUE TITLE
Calculate Path length - Global

### ISSUE THREAD

**Issue by mitemijalkov** [softmatterlab/Braph-2.0-Matlab#98]
Calculate the path length of a graph (BU, WU graphs). Calculate the In and Out -  path length of the graph in the case of BD and WD graphs.

The path length is simply the average of the nodal path lengths for all nodes in the graph. The average can be performed in three ways:
1) Simple average
2) within connected subgraphs
3) Harmonic mean

Once these are implemented, we can discuss about additional ways to perform the averaging procedure. Also, if a graph is disconnected, path length calculated as 1) returns NaN. Based on what we need, we can have additional ways to deal with it (return 0, output warning, etc..).

**Comment by egolol** [comment]
within connected subgraphs... what does that mean?

**Comment by mitemijalkov** [comment]
The average would be taken only between the nodes that have at least 1 connection in the network (so that the path length is a real number and not a nan). I think nanmean is the function (although I am not sure if that function is part of the core matlab or comes with a toolbox)
